{
    "1":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en"
        },
        "info":"ks-46.105.123.104 78786",
        "extra":{
            "am_un":"kikoball@live.com",
            "am_pw":"dNJG&H*p2D",
            "_fb_un":"+14752223111",
            "_fb_pw":"5M;`Wn.R2`"
        },
        "args":{
            "skip":"f",
            "close":true,
            "cashout":true
        }
    },
    "2":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"fr,fr-fr,en-us,en"
        },
        "info":"78786 autosurf disabled",
        "extra":{
            "eb_url":"",
            "am_url":"78786"
        }
    },
    "3":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"142.4.213.7",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-142.4.213.7 can't login from ca ip",
        "extra":{
            "am_un":"getrefer@gmail.com",
            "am_pw":"refer1987",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "4":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"142.4.213.7",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-142.4.213.7 79016 autosurf disabled",
        "extra":{
            "eb_url":"saythx",
            "am_url":""
        }
    },
    "5":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"192.99.2.120",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-192.99.2.120",
        "extra":{
            "am_un":"triblefox@outlook.com",
            "am_pw":"hard0152",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "6":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"192.99.2.120",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-192.99.2.120, 85271 autosurf disabled",
        "extra":{
            "eb_url":"saythx",
            "am_url":""
        }
    },
    "7":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.24",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.24",
        "extra":{
            "am_un":"laytik@hotmail.com",
            "am_pw":"tictic5656",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "8":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.24",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.24",
        "extra":{
            "eb_url":"laytik",
            "am_url":"81484"
        }
    },
    "9":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"204.44.73.134",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-204.44.73.134",
        "extra":{
            "am_un":"urmosy@outlook.com",
            "am_pw":"RjW0iyHMvP",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "10":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"204.44.73.134",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-204.44.73.134 eb-triblefox banned, am-89678 autosurf disabled",
        "extra":{
            "eb_url":"",
            "am_url":""
        }
    },
    "11":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"204.44.73.135",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-204.44.73.135",
        "extra":{
            "am_un":"ahgohub@outlook.com",
            "am_pw":"gMtf6rVYtm",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "12":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "info":"vm-204.44.73.135",
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"204.44.73.135",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "extra":{
            "eb_url":"saythx",
            "am_url":"99042"
        }
    },
    "13":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.105",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"dgc-202.144.193.105",
        "extra":{
            "am_un":"jonnyhill8@outlook.com",
            "am_pw":"MrN8I81UdY",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "14":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.105",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"dgc-202.144.193.105",
        "extra":{
            "eb_url":"cnabox",
            "am_url":""
        }
    },
    "15":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.106",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "extra":{
            "am_un":"billykerlin@outlook.com",
            "am_pw":"DEHUFBsT7J",
            "fb_un":"",
            "fb_pw":""
        },
        "info":"dgc-202.144.193.106",
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "16":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.106",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"dgc-202.144.193.106 89006 autosurf disabled",
        "extra":{
            "eb_url":"cnabox",
            "am_url":""
        }
    },
    "17":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"104.223.15.230",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "extra":{
            "am_un":"saythx@hotmail.com",
            "am_pw":"say19746",
            "fb_un":"",
            "fb_pw":""
        },
        "info":"do-104.131.16.129(expired), using gdb-104.223.15.230",
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "18":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"104.223.15.230",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"do-104.131.16.129(expired), using gdb-104.223.15.230",
        "extra":{
            "eb_url":"cnabox",
            "am_url":"82719"
        }
    },
    "19":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"80.78.132.90",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "extra":{
            "am_un":"robotq@live.com",
            "am_pw":"",
            "fb_un":"",
            "fb_pw":""
        },
        "info":"kts-80.78.132.90",
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "20":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"80.78.132.90",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"kts-80.78.132.90",
        "extra":{
            "eb_url":"kikoball",
            "am_url":""
        }
    },
    "21":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"91.121.83.109",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-91.121.83.109, ks-62.210.169.229 expired",
        "extra":{
            "am_un":"cnabox@hotmail.com",
            "am_pw":"free7878",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "22":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"fr,fr-fr,en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"91.121.83.109",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"ks-91.121.83.109, ks-62.210.169.229 expired, 78790 autosurf disabled",
        "extra":{
            "eb_url":"",
            "am_url":""
        }
    },
    "23":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.25",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.25, 192.169.188.105 expired",
        "extra":{
            "am_un":"mileybau@outlook.com",
            "am_pw":"gisle78164",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "24":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.25",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.25, 192.169.188.105 expired, 85341 autosurf disabled",
        "extra":{
            "eb_url":"laytik",
            "am_url":""
        }
    },
    "25":{
        "task":"am_emu",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.171",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"dgc-202.144.193.171",
        "extra":{
            "am_un":"reminde.com@gmail.com",
            "am_pw":"nxix8734",
            "fb_un":"",
            "fb_pw":""
        },
        "args":{
            "skip":"f",
            "close":false,
            "cashout":true
        }
    },
    "26":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"202.144.193.171",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"dgc-202.144.193.171",
        "extra":{
            "eb_url":"getrefer",
            "am_url":"112266"
        }
    },
    "27":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.34",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.34",
        "extra":{
            "eb_url":"laytik",
            "am_url":"99042"
        }
    },
    "28":{
        "task":"ameb",
        "browser":"firefox",
        "driver":{

        },
        "prefs":{
            "intl.accept_languages":"en-us,en",
            "network.proxy.type":1,
            "network.proxy.socks":"173.254.219.46",
            "network.proxy.socks_port":1080,
            "network.proxy.socks_remote_dns":true
        },
        "info":"vm-173.254.219.46",
        "extra":{
            "eb_url":"laytik",
            "am_url":"82719"
        }
    }
}
